name: CI

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: dotnet build GenerateBindings
      run: |
        dotnet build GenerateBindings -c Debug
        dotnet build  GenerateBindings -c Release

    - name: msbuild SDL3
      run: |
        msbuild -restore SDL3-CS.sln /p:Configuration=Debug
        msbuild -restore SDL3-CS.sln /p:Configuration=Release

    - name: dotnet build SDL3.Core
      run: |
        dotnet build SDL3/SDL3.Core.csproj -c Debug
        dotnet build SDL3/SDL3.Core.csproj -c Release
