name: CI

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: dotnet build GenerateBindings
      run: |
        dotnet build --project GenerateBindings -c Debug
        dotnet build --project GenerateBindings -c Release

    - name: msbuild SDL3
      run: |
        msbuild SDL3-CS.sln /p:Configuration=Debug /p:Platform=x86
        msbuild SDL3-CS.sln /p:Configuration=Release /p:Platform=x86

    - name: dotnet build SDL3.Core
      run: |
        dotnet build --project SDL3/SDL3.Core.csproj -c Debug
        dotnet build --project SDL3/SDL3.Core.csproj -c Release
